#ifndef CNCJS_CLIENT_H
#define CNCJS_CLIENT_H

#include <Arduino.h>

#include <WiFi.h>
#include <HTTPClient.h>

#include <WebSocketsClient.h>
#include <SocketIOclient.h>

#include <ArduinoJson.h>

#include "MachineCommand.h"
#include "MachineState.h"


class CNCjsClient
{
public:

    // ========================================================
    // Lifecycle
    // ========================================================

    void begin(
        MachineState& machineState
    );

    void update();


    // ========================================================
    // Status
    // ========================================================

    enum class CNCjsStatus
    {
        Offline,
        WiFiConnecting,
        Authenticating,
        Connecting,
        WaitingForLists,
        SelectionRequired,
        OpeningController,
        Ready,
        Error
    };


    CNCjsStatus status() const;


    // ========================================================
    // Connection status
    // ========================================================

    bool wifiConnected() const;

    bool authenticated() const;

    bool socketConnected() const;


    // ========================================================
    // Serial ports
    // ========================================================

    int portCount() const;

    const char* port(
        int index
    ) const;


    // ========================================================
    // Controllers
    // ========================================================

    int controllerCount() const;

    const char* controller(
        int index
    ) const;


    // ========================================================
    // Controller selection
    // ========================================================

    bool controllerSelectionReady() const;

    int selectedController() const;

    const char* selectedControllerName() const;

    int selectedPort() const;

    const char* selectedPortName() const;


    bool selectController(
        int portIndex,
        int controllerIndex
    );


    void chooseController();


    // ========================================================
    // Active controller
    // ========================================================

    bool controllerReady() const;

    const char* controllerPort() const;

    const char* controllerType() const;

    int controllerBaudrate() const;


    // ========================================================
    // Controller communication
    // ========================================================

    bool openSelectedController();

    bool openController(
        const char* port,
        const char* controllerType,
        int baudrate
    );


    bool execute(
        const MachineCommand& command
    );


    // ========================================================
    // G-code
    // ========================================================

    bool sendGcode(
        const char* gcode
    );

    bool sendGcode(
        const char* port,
        const char* gcode
    );


    // ========================================================
    // CNCjs controller commands
    // ========================================================

    bool sendCommand(
        const String& command
    );


    bool jogCancel();
    bool feedHold();
    bool resume();
    bool reset();

    bool sendRealtime(
        uint8_t command
    );


private:

    // ========================================================
    // CNCjs server
    // ========================================================

    String serverHost_;

    uint16_t serverPort_ =
        8000;

    IPAddress serverIP_;


    void loadServerSettings();

    void saveServerSettings(
        const char* host,
        uint16_t port
    );


    // ========================================================
    // Socket.IO
    // ========================================================

    SocketIOclient socketIO;

    String token;


    // ========================================================
    // State
    // ========================================================

    CNCjsStatus currentStatus =
        CNCjsStatus::Offline;


    bool authenticatedState =
        false;

    bool socketConnectedState =
        false;


    // ========================================================
    // Machine state
    // ========================================================

    MachineState* machineState_ =
        nullptr;


    void updateMachineState(
        JsonObject status,
        JsonObject parserstate
    );


    MachineStatus machineStatusFromCNCjs(
        const char* activeState
    ) const;


    // ========================================================
    // Pending machine command
    //
    // Commands generated by the pendant are first stored here.
    //
    // update() sends the pending command at 20 Hz.
    // ========================================================

    MachineCommand pendingCommand_;

    bool commandDirty_ =
        false;

    unsigned long lastCommandSendTime_ =
        0;

    static constexpr unsigned long COMMAND_SEND_INTERVAL =
        50;


    bool sendPendingCommand();


    // ========================================================
    // Serial ports
    // ========================================================

    static constexpr int MAX_PORTS =
        8;

    String ports[MAX_PORTS];

    int numberOfPorts =
        0;

    bool listRequested =
        false;


    // ========================================================
    // Controllers
    // ========================================================

    static constexpr int MAX_CONTROLLERS =
        8;

    String controllers[MAX_CONTROLLERS];

    int numberOfControllers =
        0;


    // ========================================================
    // Lists received
    // ========================================================

    bool startupReceivedState =
        false;

    bool portListReceivedState =
        false;


    // ========================================================
    // Selected controller
    // ========================================================

    int selectedControllerIndex =
        -1;

    String selectedControllerNameState;

    int selectedPortIndex =
        -1;

    String selectedPortNameState;

    bool controllerSelectionReadyState =
        false;


    // ========================================================
    // Active controller
    // ========================================================

    String activeControllerPortState;

    String activeControllerTypeState;

    int activeControllerBaudrateState =
        0;

    bool controllerReadyState =
        false;


    // ========================================================
    // Connection
    // ========================================================

    bool connectWiFi();

    bool resolveCNCjs();

    bool authenticate();

    void connectSocket();

    void requestPortList();


    // ========================================================
    // Controller selection
    // ========================================================

    void loadControllerList();

    int loadSavedController();

    String loadSavedControllerName();

    String loadSavedPortName();


    void saveSelectedController(
        int index,
        const char* name
    );


    void saveSelectedPort(
        const char* port
    );


    int findControllerByName(
        const char* name
    ) const;


    int findPortByName(
        const char* name
    ) const;


    int baudrateForController(
        const char* controllerType
    ) const;


    // ========================================================
    // Socket.IO
    // ========================================================

    void handleSocketEvent(
        socketIOmessageType_t type,
        uint8_t* payload,
        size_t length
    );


    static CNCjsClient* instance;


    static void socketIOEvent(
        socketIOmessageType_t type,
        uint8_t* payload,
        size_t length
    );
};


#endif